### PR TITLE
Clean up wording and formatting of operational flows section.

### PR DESCRIPTION
**Pull request by tylerbutler**

### CODE REVIEW

**Comment by karvell** [comment]
For step 11 in the add a place flow, can you replace with:
11. The user has now added the Storage Provider as a place. For the operational flow on browsing, opening, and saving files, see the next sections. 

For #1 in Browsing and opening files, let's updated it to remove references to using the Ecosystem. We're just going to make the shortcut a required operations (to cut down on the confusion... we already made this a requirement in another topic):

1. Get the Root Container URL: |Office iOS| calls :ref:`GetRootContainer (bootstrapper)` to obtain a Root Container URL.

**Comment by tylerbutler** [comment]
@karvell Your feedback should now be addressed.

**Comment by tylerbutler** [comment]
@karvell Last chance to comment before I merge this in. :smiling_imp:

**Comment by karvell** [comment]
looks good.

**Pull request merged**
