### PR TITLE
Add docs on new document creation

### PR DESCRIPTION
**Pull request by tylerbutler**
Fixes issue #2.

### CODE REVIEW

**Comment by MarcinJuraszek** [comment]
`editNew` is not enough. `newTpl` query string parameter is required too.

**Comment by tylerbutler** [comment]
@chrisbro-MSFT confirmed yesterday that it's not. It'll default to the blank template, which is the correct behavior.

**Comment by MarcinJuraszek** [comment]
hmm, I'll look into it, because I'm pretty sure it it. And even if it's not, if you don't pass it Excel doesn't work because of the `newWorkbook` mode, remember?

**Comment by MarcinJuraszek** [comment]
OK, Chris is right. But there is still the Excel issue we should remember about.

**Comment by chrisbro-MSFT** [comment]
I sent the fix for &new=1 for Excel through triage today.

**Pull request merged**
